apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Values.labels.version }}
    branch: {{ .Values.labels.branch }}
    env: {{ .Values.labels.env }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      version: {{ .Values.labels.version }}
      env: {{ .Values.labels.env }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: {{ .Values.labels.version }}
        branch: {{ .Values.labels.branch }}
        env: {{ .Values.labels.env }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        env: # 设置环境变量
        {{- range .Values.envVars }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
