apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secret.yaml
images:
- name: jackiechenopus/flask-demo
  newTag: a68b1f14175ba53c2441e4005dc46decead68835
