replicaCount: 1

image:
  repository: 'jackiechenopus/flask-demo'
  tag: 'b32140a6b74c5b28d8ae1b26da9a2cc82aa069ed'
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

labels:
  version: "v1.0.0"          # 应用版本
  application: "flask-demo"  # 应用名称
  branch: master             # Git 分支
  env: staging               # 运行环境，如 production、staging、development

envVars:                     # 容器内的环境变量
  - name: APP_ENV
    value: "staging"         # 应用运行环境变量
  - name: LOG_LEVEL
    value: "debug"           # 日志级别
  - name: FEATURE_FLAG
    value: "enabled"         # 功能开关

resources:                   # 容器资源配置（可选）
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"